<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-T3R8PGS" name="test.LinkedInLoginTestUsingPageFactory" tests="2" failures="0" timestamp="3 Aug 2022 05:53:25 GMT" time="24.579" errors="1">
  <testcase name="testLinkedInLoginUsingPagefactoryUsingdataprovider" time="0.000" classname="test.LinkedInLoginTestUsingPageFactory">
    <error type="org.testng.TestNGException" message="
Method public void test.LinkedInLoginTestUsingPageFactory.testLinkedInLoginUsingPagefactoryUsingdataprovider(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : xyz">
      <![CDATA[org.testng.TestNGException: 
Method public void test.LinkedInLoginTestUsingPageFactory.testLinkedInLoginUsingPagefactoryUsingdataprovider(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : xyz
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- testLinkedInLoginUsingPagefactoryUsingdataprovider -->
  <testcase name="testLinkedInLoginUsingPagefactory" time="24.579" classname="test.LinkedInLoginTestUsingPageFactory"/>
</testsuite> <!-- test.LinkedInLoginTestUsingPageFactory -->
